# Generated by Django 4.2 on 2024-06-18 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100, unique=True, verbose_name='Бюджет')),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'бюджет',
                'verbose_name_plural': 'Годовые бюджеты',
                'ordering': ('my_order',),
            },
        ),
        migrations.CreateModel(
            name='TelegramText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Идентификатор')),
                ('text', models.TextField(max_length=4096, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'текст',
                'verbose_name_plural': 'Текстовое наполнение',
            },
        ),
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='Телеграм id')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ник телеграм')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Номер телефона')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Рост (см)')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Вес (кг)')),
                ('budget', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бюджет годовой')),
                ('questionnaire_completed', models.BooleanField(default=False, verbose_name='Анкета заполнена')),
                ('curr_input', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Телеграм id')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.event')),
            ],
            options={
                'verbose_name': 'Рабочее время',
                'verbose_name_plural': 'Рабочее время',
            },
            bases=('schedule.event',),
        ),
    ]
