# Generated by Django 4.2 on 2024-06-19 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_alter_calendar_options_alter_event_options'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='consultation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='schedule.event', verbose_name='Консультация'),
        ),
        migrations.DeleteModel(
            name='WorkingTime',
        ),
    ]
