# Generated by Django 4.2 on 2024-06-25 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_alter_calendar_options_alter_event_options'),
        ('core', '0003_alter_tguser_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='consultation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='schedule.event', verbose_name='Консультация'),
        ),
    ]
